// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Get environment variables - must start with VITE_ in Vite projects
const getEnv = (key: string, fallback: string): string => {
  const value = (import.meta.env[key] as string | undefined) || fallback;
  if (!value || value === "undefined" || value === "null") {
    console.error(`Missing or invalid environment variable: ${key}`);
    return fallback;
  }
  return value;
};

const SUPABASE_URL = getEnv('VITE_SUPABASE_URL', '');
const SUPABASE_PUBLISHABLE_KEY = getEnv('VITE_SUPABASE_PUBLISHABLE_KEY', '');

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error("Supabase configuration error - check environment variables");
}

export const supabase = createClient<Database>(
  SUPABASE_URL || "https://placeholder.supabase.co",
  SUPABASE_PUBLISHABLE_KEY || "placeholder-key",
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
    },
  }
);